### ISSUE TITLE
IPv6 validation seems to not check zone_id correctly

### ISSUE THREAD

**Issue by harlowja** [drkjam/netaddr#140]
Looking at the following:

https://tools.ietf.org/html/rfc4007#page-15

It appears that the zone_id has certain restrictions but netaddr isn't checking those.

```
>>> x = 'fe80::1%'
>>> netaddr.valid_ipv6(x)
True
```

Apparently one of the checks is that the zone_id can't be null (which it is in the above).

**Comment by sileht** [comment]
I don't think this is a netaddr issue, this method is just a wrapper around _socket methods.
The wrapper and the builtin socket methods implementation doesn't have such issue.

```
>>> import netaddr, netaddr.fbsocket
>>> x = 'fe80::1%'
>>> netaddr.valid_ipv6(x)
False
>>> netaddr.fbsocket.inet_pton(netaddr.fbsocket.AF_INET6, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/cdt.C6o62gPN/venv/local/lib/python2.7/site-packages/netaddr/fbsocket.py", line 196, in inet_pton
    [_pack('>H', int(i, 16)) for i in l_suffix]
ValueError: invalid literal for int() with base 16: '1%'
```

And my _socket module work as expected, so that looks like yours is buggy :)

```
>>> import _socket
>>> _socket.inet_pton(_socket.AF_INET6, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.error: illegal IP address string passed to inet_pton
```

**Comment by sileht** [comment]
I think at least on Linux, valid_ipv6 doesn't support zone_id at all.

**Comment by jstasiak** [comment]
> Is `fe80::1%eth1` a valid IPv6? Should it be identifyable as such?

These are great questions. I'm entirely sure right now, need to sleep on this. I don't think this library is prepared for IPv6 scope zones.
