### ISSUE TITLE
Leading zero on ips

### ISSUE THREAD

**Issue by rlucca** [drkjam/netaddr#180]
Hi there,

I was doing some tests and I get this error with leading zeros. For me, all tests should be considered correct. Am I wrong?

```
>>> IPAddress('8.8.8.8').version
4
>>> IPAddress('008.8.8.8').version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 306, in __init__
    'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from '008.8.8.8'
>>> IPAddress('8.8.08.8').version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 306, in __init__
    'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from '8.8.08.8'
```
```
# pip search netaddr
netaddr (0.7.19)  - A network address manipulation library for Python
  INSTALLED: 0.7.19 (latest)
```

**Comment by rlucca** [comment]
I found that this case doesnt make sense.
